const siteUrl = "https://copywriterpro.ai";

module.exports = {
  siteUrl,
  exclude: [
    "/account",
    "/app/ai-ghostwriter",
    "/app/ai-write-along",
    "/about",
    "/app",
    "/bookmarks",
    "/contenttools/categories",
    "/contenttools/tools",
    "/draft",
    "/notice/update",
    "/pricing-new",
    "/processing",
    "/reward",
    "/playground22",
    "/account-verification",
    "/auth",
    "/email-verification",
    "/extension-auth",
    "/extension/access",
    "/payment/canceled",
    "/payment/success",
    "/app/Blog",
    "/tutorial/tools/*",
    "/bd-pricing",
    "/new/*",
  ],
};
